### ISSUE TITLE
[ERROR]: Failed to download singularity image

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#472] opened 2020-10-26 08:16 UTC
**Describe the bug**
The latest feature to download the singularity image doesn't work. And reports the error.

`Failed to pull singularity image from docker://hassanf/balsamic:release_v6.0.1`

**To Reproduce**
Run
`balsamic init container -o ~/BALSAMIC/balsamic_container/`

**Expected behavior**
If failing, the log message needs to be captured in the terminal.

**Screenshots**
<img width="954" alt="error" src="https://user-images.githubusercontent.com/6302819/97148032-c2f8f580-176a-11eb-8b14-2fe722458d98.png">

**Version (please complete the following information):**
balsamic, version 6.0.1

**Solution**
check if problem is due to `out_dir` 
https://github.com/Clinical-Genomics/BALSAMIC/blob/e2e316ceb3f054072abf7d76204300215678aa94/BALSAMIC/commands/init/container.py#L74

**Comment by hassanfa** [comment] 2020-12-09 15:57
I can't reproduce this. Tried on Hasta, and on my local machine but works fine. 😕

**Comment by hassanfa** [comment] 2021-03-02 15:08
This is fixed in 7.0.0

**Closed by hassanfa** 2021-03-02 15:08 UTC
