### ISSUE TITLE
Check that tumor samples come from the same individual

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/BALSAMIC#300] opened 2020-04-22 06:55 UTC
Customer request from the Scout user meeting of March 4rth: https://github.com/Clinical-Genomics/scout/issues/1679

**Comment by hassanfa** [comment] 2020-04-22 07:00
Issue 300!

![image](https://user-images.githubusercontent.com/1086877/79950707-bf14af80-8477-11ea-8160-d8b59cbbb86d.png)

**Comment by hassanfa** [comment] 2021-03-15 14:30
updates from cancer bioinfo meeting:

Check sample is from same individual:
1. Look into external softwares that do this (example GATK or Picard)
2. Simple germline mutation matching

**Comment by hassanfa** [comment] 2021-05-20 20:13
Solution: https://github.com/brentp/somalier

Only useful in tumor-normal analysis.

**Comment by ashwini06** [comment] 2022-03-17 13:44
To Do in Project planning for upcoming quarter https://github.com/Clinical-Genomics/project-planning/issues/369

**Comment by fevac** [comment] 2022-11-28 10:37
Taken care on:

- https://github.com/Clinical-Genomics/project-planning/issues/375
- https://github.com/Clinical-Genomics/BALSAMIC/pull/1017

**Comment by pbiology** [comment] 2022-12-13 11:56
duplicate of https://github.com/Clinical-Genomics/project-planning/issues/375

**Closed by pbiology** 2022-12-13 11:56 UTC
Labels: Enhancement
