### ISSUE TITLE
Bioinformatic workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/BALSAMIC#302] opened 2020-04-22 14:00 UTC

**Comment by hassanfa** [comment] 2020-04-22 14:05
I think some text is missing. Is this doc related?

**Comment by annaengstrom** [comment] 2020-04-22 14:25
Define MVP: 
- QC parameters for pipeline
- Understandable error messages
- Variant filtering strategy / options
etc

https://github.com/Clinical-Genomics/BALSAMIC

**Comment by moonso** [comment] 2020-05-08 09:50
Hi, I'm moving this to the project repo. I think the issue is to vague to be here.
It now lives here https://github.com/Clinical-Genomics/cgp-cancer-in-weekly-production/issues/6

**Closed** 2020-05-08 12:40 UTC
