### ISSUE TITLE
Mutation tumor burden

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/BALSAMIC#894] opened 2022-03-25 07:08 UTC
Hi 
I wonder if it will be possible to get a meassure of the mutational tumor burden in balsamic pipeline
It is very useful for specific diagnoses

thanks

Teresita

**Comment by ivadym** [comment] 2023-02-01 13:28
Closing this issue as it is a duplicate of https://github.com/Clinical-Genomics/BALSAMIC/issues/912, which is an ongoing project.

@Clinical-Genomics/cancer-bioinfo

**Closed by ivadym** 2023-02-01 13:28 UTC
Labels: Needs Refinement
