### ISSUE TITLE
[User Story] <HELP - missed variant in my analysis>

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/BALSAMIC#1411] opened 2024-03-06 15:12 UTC
### Need

As a clinical geneticist I would like to find disease causing variants when I perform my analysis!

### Suggested approach

When I perform my filtering I would lika to se variants that are NOT COMMON compared to the human genome (Hg19)

### Considered alternatives

No alternatives what so ever!

### Deviation

https://scout.scilifelab.se/cust002/F0042600-2

### System requirements assessed

- [ ] Yes, I have reviewed the system requirements

### Requirements affected by this story

Do not understand...

### Risk assessment needed

- [X] Needed
- [ ] Not needed

### Risk assessment

?

### Anything else?

I have performed an analysis on affected tissue (no normal tissue) and I perform my analysis (Screening UBA1-gene) i get no variants - but if I look att IGV the variant is there (approx heteroz). X:47058450

We have rerun the sample trough MIP and that pipeline detects the variant. 

We would like to use Balsamic for this analysis since we are looking from mosaic variants in this gene - and with low mosaicism that will be missed using MIP. 

Please advice how to proceed.

**Comment by mathiasbio** [comment] 2024-03-07 09:56
Hi Kicki! Thanks for bringing this to our attention...we completely agree that this variant should not be filtered out. 

I have looked into it and I think the issue here comes from how balsamic has been built to accommodate such varied types of input data, and in the case of exome-samples it has been treated as standard panel-samples where the coverage is assumed to be higher. But it really should have been taken into account from the start that exome-samples generally have a lot lower coverages than smaller panels, and the filtering-strategy should reflect that. We're going to make a quick fix of this and try to deploy it as quickly as possible so it won't happen again.

But in terms of this particular case, is there anything we can do to help?

**Comment by KickiLagerstedt** [comment] 2024-03-08 08:58
> Hi Kicki! Thanks for bringing this to our attention...we completely agree that this variant should not be filtered out.
> 
> I have looked into it and I think the issue here comes from how balsamic has been built to accommodate such varied types of input data, and in the case of exome-samples it has been treated as standard panel-samples where the coverage is assumed to be higher. But it really should have been taken into account from the start that exome-samples generally have a lot lower coverages than smaller panels, and the filtering-strategy should reflect that. We're going to make a quick fix of this and try to deploy it as quickly as possible so it won't happen again.
> 
> But in terms of this particular case, is there anything we can do to help?

We rerun it through MIP and the variant was called.
I will now go through every case since January manually in IGV in order to see if we have missed some other pathological variants.

Please let me know when this is fixed!

Thank You!

**Comment by mathiasbio** [comment] 2024-03-08 09:13
Hi, 

Maybe some more information could be helpful for you here. Most exome analyses that are ordered here are sequenced at 200M read-pairs, whereas this case was only sequenced at 60M read-pairs. For the usual exome-analyses the filter I mentioned above should be much less of an issue as about 98% of the entire target-panel in those cases are covered above 100X, which is the read-depth filter that I was referring to, and most of the remaining 2% of the bases are also likely problematic regions. For the 60M read-pair case we are talking about here about 60% of the target bases was covered above 100X.

So what I'm trying to say is that you could narrow your worries down to the cases which has been ordered below 200 M read-pairs. If you want to I could help you identify the potential risk cases!

Kind regards,
Mathias

**Comment by KickiLagerstedt** [comment] 2024-03-14 12:21
So essentially every case we have ordered through the Balsamic pipeline with the application EXOKTTR060 we are now worried about.... Could You please look into this!

**Comment by AnnHam** [comment] 2024-03-14 14:30
Hej, 

Can you look into case **2023-35883-03** (F0054403-2) - why isn't the variant in PIK3CA called? The coverage for the variant is 582X (mean coverage is 370X), the alternative allele 60 reads out of 582 (VAF 10%). variant chr3:178,936,083 (hg19). We now sent in another sample from this patient **2023-35962-04** (F0054403-3) and that's how we found the variant. In the first analysis it seems as if all variants that are mosaic is filtered out - in my gene list (somatic overgrowth and vascular malformations) I only get variants with a VAF around 50%.

**Comment by mathiasbio** [comment] 2024-03-14 15:41
Absolutely, I will collect a list of all the affected cases that has been run through balsamic with the apptag EXOKTTR060. We have already developed a fix for the issue, with a specific set of settings for exome samples, it has not been validated yet but it makes sense logically given the coverages we expect for this amount of input-reads. We should be able to re-run your cases with these new settings, but I have to discuss it with our production managers first! 

I will also look into the case you mentioned @AnnHam ! 🙏

**Comment by karlnyr** [comment] 2024-03-15 10:19
> > Hi Kicki! Thanks for bringing this to our attention...we completely agree that this variant should not be filtered out.
> > I have looked into it and I think the issue here comes from how balsamic has been built to accommodate such varied types of input data, and in the case of exome-samples it has been treated as standard panel-samples where the coverage is assumed to be higher. But it really should have been taken into account from the start that exome-samples generally have a lot lower coverages than smaller panels, and the filtering-strategy should reflect that. We're going to make a quick fix of this and try to deploy it as quickly as possible so it won't happen again.
> > But in terms of this particular case, is there anything we can do to help?
> 
> We rerun it through MIP and the variant was called. I will now go through every case since January manually in IGV in order to see if we have missed some other pathological variants.
> 
> Please let me know when this is fixed!
> 
> Thank You!

Hej @KickiLagerstedt, am I understanding correctly that you have run the same sample through MIP through us? Is the sample not a tumor sample or is it a mosaic sample?

**Comment by mathiasbio** [comment] 2024-03-15 15:08
Hi again @AnnHam I have looked at your case and this variant should also definitely have been called. I took a look at the bamfile and I believe the issue is the same as has recently been discovered internally (https://github.com/Clinical-Genomics/BALSAMIC/issues/1396) and which is also going to be adressed in the update where we will create more exome-appropriate filters. 

In short it seems that VarDict does not do strand-bias filtering in the most optimal way...
At some point during the development of the pipeline, a flag was implemented which forces VarDict to only call variants once for overlapping mates in a read-pair, which makes sense. However when this flag is implemented it also specifically calls only reads in either the forward or reverse of the mates, which creates an artificial strand-bias which VarDict then filters out. This is an issue mostly for samples with quite low insert-sizes which produces more overlapping mates.

In the fix we're going to implement as soon as possible we're going to remove this flag, and more long-term we're planning to replace VarDict with TNscope which should look at strand-bias in a more sophisticated way.

**Comment by mathiasbio** [comment] 2024-03-21 16:10
Hi again,

@KickiLagerstedt @AnnHam 

We have now merged the fixes to these issues in the develop-branch and will start validation now. Hopefully it will be deployed in production after next week. Then we can begin re-running any of the relevant affected cases! But I wonder if it would be good if you opened a ticket in SuSy regarding the communication of which cases might need a re-analysis, where we could continue this talk more freely as these issues on github are open to the internet :) 

Kind regards,
Mathias

**Comment by henrikstranneheim** [comment] 2024-03-25 08:32
Done according to @mathiasbio

**Closed by henrikstranneheim** 2024-03-25 08:32 UTC
Labels: User-Story

**Comment by KickiLagerstedt** [comment] 2024-03-25 09:49
@mathiasbio

"you opened a ticket in SuSy regarding the communication of which cases might need a re-analysis,"

What is SuSy?

**Comment by KickiLagerstedt** [comment] 2024-03-25 09:52
@karlnyr 

The sample has a somatic mutation. 
DNA is prepared from bone marrow or blood. (affected tissue)

**Comment by mathiasbio** [comment] 2024-03-25 10:34
Sorry I'm using internal CG-terminology here! SuSy is what we call the support-system, the place where we communicate around orders and deliveries. I opened up a ticket here and added you as collaborators: https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=67840
