### ISSUE TITLE
cyvcf2 and Cython not in requirements.txt

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/BALSAMIC#409] opened 2020-09-09 16:32 UTC
**Describe the bug**
Merging https://github.com/Clinical-Genomics/BALSAMIC/pull/349 introduced an error where cyvc2 and cython are missing.

**To Reproduce**
install BALSAMIC via `pip install -r requirements.txt -e .` and type: `balsamic`

**Expected behavior**
No error on missing package or module

**Version (please complete the following information):**
`latest 5.1.0+` 

**Additional context**
Add cython and cyvcf2 to requirements.txt

**Comment by hassanfa** [comment] 2020-09-09 16:34
@ashwini06 could you please look into this? Installing cyvcf2<0.10.0 and cython fixes the issue, as we have it in .travis.yml file. But we have to fix it.

**Comment by ashwini06** [comment] 2020-09-10 07:10
@hassanfa I couldn't reproduce the mentioned expected error. I could successfully install balsamic via `pip install -r requirements.txt -e .` and run it. Here is the screenshot. 

<img width="947" alt="Screenshot 2020-09-10 " src="https://user-images.githubusercontent.com/6302819/92692361-55247600-f344-11ea-84c1-707f9e3a6eb7.png">

Earlier, this issue was fixed by adding `cyvcf2` to dependencies in `BALSAMIC/conda/balsamic.yaml`
And in `.travis.yml` we added this 
 ```
install:
  - pip install cython
  - pip install pygraphviz pygments 'cyvcf2<0.10.0'
```

which solved Travis build issues.

**Comment by hassanfa** [comment] 2020-09-10 07:30
cyvcf2<0.10.0 and cython have to be in requirements.txt. It is not failing on travis, since we install it before `pip install -r `:

![image](https://user-images.githubusercontent.com/1086877/92694749-c9ace400-f347-11ea-826c-d41c4d2c8249.png)

But I remember there was a issue with this, and we added it outside requirements.txt to make build pass.

**Comment by hassanfa** [comment] 2020-09-10 07:31
If the fix is as simple as adding to `requirements.txt` file and removing from `.travis.yml`, then a small PR should do the trick.

**Closed** 2020-09-11 12:08 UTC
